name: CI

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install deps
        run: |
          sudo apt install -y gfortran python3-dev libomp-15-dev lcov intel-mkl
      - uses: Swatinem/rust-cache@v2
      - name: fmt
        run: |
          make fmt
          git diff --exit-code
      - name: test
        run: |
          make test
